# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "thin-auth-ntlm"
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexey Borzenkov"]
  s.date = "2013-12-03"
  s.description = "Adds Thin::Backends::NTLMTcpServer that can be used instead of Thin::Backends::TcpServer"
  s.email = "snaury@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.txt"
  ]
  s.files = [
    "LICENSE.txt",
    "README.txt",
    "Rakefile",
    "VERSION.yml",
    "lib/thin-auth-ntlm.rb",
    "lib/thin/ntlm/backends/tcp_server.rb",
    "lib/thin/ntlm/connection.rb",
    "thin-auth-ntlm.gemspec"
  ]
  s.homepage = "https://github.com/snaury/thin-auth-ntlm"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.14"
  s.summary = "Allows you to force NTLM authentication on Thin TCP servers."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thin>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<rubysspi-server>, [">= 0.0.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
    else
      s.add_dependency(%q<thin>, [">= 1.0.0"])
      s.add_dependency(%q<rubysspi-server>, [">= 0.0.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    end
  else
    s.add_dependency(%q<thin>, [">= 1.0.0"])
    s.add_dependency(%q<rubysspi-server>, [">= 0.0.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
  end
end
