# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{thin-auth-ntlm}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexey Borzenkov"]
  s.date = %q{2009-08-13}
  s.email = %q{snaury@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.txt"
  ]
  s.files = [
    "LICENSE.txt",
     "README.txt",
     "Rakefile",
     "VERSION.yml",
     "lib/thin-auth-ntlm.rb",
     "lib/thin/ntlm/backends/tcp_server.rb",
     "lib/thin/ntlm/connection.rb",
     "thin-auth-ntlm.gemspec"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{Allows you to force NTLM authentication on Thin TCP servers.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thin>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<rubysspi-server>, [">= 0.0.1"])
    else
      s.add_dependency(%q<thin>, [">= 1.0.0"])
      s.add_dependency(%q<rubysspi-server>, [">= 0.0.1"])
    end
  else
    s.add_dependency(%q<thin>, [">= 1.0.0"])
    s.add_dependency(%q<rubysspi-server>, [">= 0.0.1"])
  end
end
